<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Naveen" failures="1" tests="9" name="com.tutorialNinja.qa.TestCase.Login" time="34.801" errors="0" timestamp="2023-11-20T19:13:15 IST" skipped="0">
  <testcase classname="com.tutorialNinja.qa.TestCase.Login" name="verifyLoginWithValidCredentials" time="3.725"/>
  <testcase classname="com.tutorialNinja.qa.TestCase.Login" name="verifyLoginWithInvalidCredentials" time="4.872">
    <failure message="expected [Warning: N match for E-Mail Address and/or Password.] but found [Warning: No match for E-Mail Address and/or Password.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Warning: N match for E-Mail Address and/or Password.] but found [Warning: No match for E-Mail Address and/or Password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.tutorialNinja.qa.TestCase.Login.verifyLoginWithInvalidCredentials(Login.java:66)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
  <testcase classname="com.tutorialNinja.qa.TestCase.Login" name="verifyLoginWithInvalidEmail" time="3.988"/>
  <testcase classname="com.tutorialNinja.qa.TestCase.Login" name="verifyLoginWithInvalidPassword" time="3.650"/>
  <testcase classname="com.tutorialNinja.qa.TestCase.Login" name="verifyLoginWithEmptyFields" time="4.109"/>
  <testcase classname="com.tutorialNinja.qa.TestCase.Login" name="verifyForgotPassowrdWorkProperly" time="3.277"/>
  <testcase classname="com.tutorialNinja.qa.TestCase.Login" name="verifyThatUserShouldLoginWithKeyboard" time="3.637"/>
  <testcase classname="com.tutorialNinja.qa.TestCase.Login" name="verifyThePlaceHolderInEmailAndPasswordField" time="3.699"/>
  <testcase classname="com.tutorialNinja.qa.TestCase.Login" name="verifyLoggingoutFromTheApplicationAndBrowsingBackUsingBrowserBackButton" time="3.844"/>
</testsuite> <!-- com.tutorialNinja.qa.TestCase.Login -->
